---
title: "visualizations and stuff"
author: "Colleen Minnihan"
date: "4/23/2021"
output: html_document
---


```{r}
library(tidyverse)
library(sf)
```


```{r}
##### RUN THIS CHUNK WHENEVER YOU READ IN THE DATA
data <- st_read("mn_acs_ss_act_pred/mn_acs_ss_act_pred.shp",
                geometry_column = "geometry",
                fid_column_name = "geometry")
# rename the census variables because their names were reformatted...
names(data)[1:28] <- 
  c("GEOID", "District", "District.Nbr", "male_5to9", "male_10to14", "male_15to17",
    "total_pop", "race_white_only", "race_Black_only", "race_Asian_only",
    "race_pacific_islander_only", "at_least_two_races", "SSI_pubassist_foodstamps",
    "med_household_inc_12mo", "house_units_w_mortgage", "med_gross_rent",
    "internet_subscrip_in_house", "perc_male_5to9", "perc_male_10to14",
    "perc_male_15to17", "perc_white_only", "perc_black_only", "perc_asian_only",
    "perc_pacific_islander_only", "perc_at_least_two_races", "perc_SSI_pubassist_foodstamps",
    "perc_house_units_w_mortgage", "perc_internet_subscription")
names(data)[93] <- c("TotalClasses")
```

```{r}
#population
Population <-
ggplot(data, aes(fill = total_pop)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma", labels = scales::comma) +
  labs(title = "Total Population", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```

```{r}
#use this
Household_Income <-
data %>%
  ggplot(aes(fill = med_household_inc_12mo)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma", labels = scales::dollar) +
  labs(title = "Median Household Income", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```

```{r}
#percent race white only.... ok so MN is veryyyyyy white
Percent_White <-
ggplot(data, aes(fill = perc_white_only)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma", labels = scales::percent) +
  labs(title = "Percent of White People", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```


```{r}
#percent race Black only
Percent_Black <-
ggplot(data, aes(fill = perc_black_only)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma", labels = scales::percent) +
  labs(title = "Percent of Black People", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```

```{r}
#percent asian only
Percent_Asian <-
ggplot(data, aes(fill = perc_asian_only)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma", labels = scales::percent_format(accuracy = 5L)) +
  labs(title = "Percent of Asian People", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```

```{r}
#percent of ppl that have computer and internet subscription in household
Percent_Internet_Sub <-
ggplot(data, aes(fill = perc_internet_subscription)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma", labels = scales::percent_format(accuracy = 5L)) +
  labs(title = "Percent Internet Subscription", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```

```{r}
#median gross rent
Gross_Rent <-
ggplot(data, aes(fill = med_gross_rent)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma", labels = scales::dollar) +
  labs(title = "Median Gross Rent", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
``` 


```{r}
#percent of ppl that receive food stamps or SSI or public assistance
Percent_Public_Assistance <-
ggplot(data, aes(fill = perc_SSI_pubassist_foodstamps)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma", labels = scales::percent) +
  labs(title = "Percent Public Assistance", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```

```{r}
#total elementary/secondary revenue
Revenue <-
ggplot(data, aes(fill = TOTALRE)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma", labels = scales::dollar) +
  labs(title = "Total Revenue", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```

```{r}
#total expenditure
Expenditure <-
ggplot(data, aes(fill = TOTALEX)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma", labels = scales::dollar) +
  labs(title = "Total Expenditure", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```

```{r}
#other local revenues
Local_Revenues <-
ggplot(data, aes(fill = LOCROTH)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma", labels = scales::dollar) +
  labs(title = "Other Local Revenues", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```

```{r}
#average composite ACT score
ACT <-
ggplot(data, aes(fill = Avg_Cmp)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma") +
  labs(title = "Average ACT Composite Score", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```

```{r}
Per_Pupil_Spending <-
  ggplot(data, aes(fill = PPCSTOT)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "B", labels = scales::dollar) +
  labs(title = "Per Pupil Total Spending", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```

```{r}
#total current spending for support services
Support_Spending <-
ggplot(data, aes(fill = TCURSSC)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma") +
  labs(title = "Total Spending for Support Services", fill = "") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(hjust = 0.5))
```

```{r, fig.width=14, fig.height=14}
#Some of these maps look incredibly identical
grid.arrange(Population, Percent_White, Percent_Black, Percent_Asian, 
             Household_Income, Gross_Rent, Percent_Public_Assistance, Percent_Internet_Sub,
             Per_Pupil_Spending, Revenue, Expenditure, Support_Spending, Local_Revenues,
             ACT, nrow = 5)
```



#filter by district
```{r}
st_paul_pub_school <- data %>%
  filter(District == "St. Paul Public School District")

red_lake_pub_school <- data %>%
  filter(District == "Red Lake Public School District")
```

```{r}
ggplot(red_lake_pub_school) + 
  geom_sf(color = "magenta") +
  ggtitle("Red Lake Public School District Profile") +
  geom_sf_text(aes(label = "Population: 5,815"), nudge_y = 0.14) +
  geom_sf_text(aes(label = "Perc. White People: 2.18%"), nudge_y = 0.09) +
  geom_sf_text(aes(label = "Median Household Income: $39,676"), nudge_y = 0.04) +
  geom_sf_text(aes(label = "Perc. w/ Internet Subscription: 59.9%"), nudge_y = -0.01) +
  geom_sf_text(aes(label = "Perc. Receiving Govt. Assist.: 67.22%"), nudge_y = -0.06)
```

```{r}
ggplot(st_paul_pub_school) + 
  geom_sf(color = "purple") +
  ggtitle("St. Paul Public School District Profile") +
  coord_sf(ylim = c(44.88,45.00)) +
  geom_sf_text(aes(label = "Population: 304,547"), nudge_y = 0.043) +
  geom_sf_text(aes(label = "Perc. White People: 56.96%"), nudge_y = 0.032) +
  geom_sf_text(aes(label = "Median Household Income: $57,876"), nudge_y = 0.021) +
  geom_sf_text(aes(label = "Perc. w/ Internet Subscription: 85.6%"), nudge_y = 0.01) +
  geom_sf_text(aes(label = "Perc. Receiving Govt. Assist.: 37.87%"), nudge_y = 0)
```

```{r}
data %>%
  mutate(highlighted_districts = ifelse(District == "Red Lake Public School District" | District == "St. Paul Public School District", "yes", "no")) %>%
  ggplot(aes(fill = highlighted_districts)) +
  geom_sf(color = "black", size = 0.2) +
  scale_fill_manual(values = c("beige","maroon4")) +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "white")) +
  ggtitle("Profile of Two Minnesota School Districts") #change title?
```


