---
title: "Survey Visualizations"
output: html_document
---

```{r eval=FALSE}
##### RUN THIS CHUNK WHENEVER YOU READ IN THE DATA
mn_acs_ss_act_pred <- st_read("mn_acs_ss_act_pred/mn_acs_ss_act_pred.shp",
                geometry_column = "geometry",
                fid_column_name = "geometry")
# rename the census variables because their names were reformatted...
names(mn_acs_ss_act_pred)[1:28] <- 
  c("GEOID", "District", "District.Nbr", "male_5to9", "male_10to14", "male_15to17",
    "total_pop", "race_white_only", "race_Black_only", "race_Asian_only",
    "race_pacific_islander_only", "at_least_two_races", "SSI_pubassist_foodstamps",
    "med_household_inc_12mo", "house_units_w_mortgage", "med_gross_rent",
    "internet_subscrip_in_house", "perc_male_5to9", "perc_male_10to14",
    "perc_male_15to17", "perc_white_only", "perc_black_only", "perc_asian_only",
    "perc_pacific_islander_only", "perc_at_least_two_races", "perc_SSI_pubassist_foodstamps",
    "perc_house_units_w_mortgage", "perc_internet_subscription")
names(mn_acs_ss_act_pred)[93] <- c("TotalClasses")
```

```{r}
mn_acs_ss_act_pred %>%
  filter(PPCSTOT > 0) %>% 
  ggplot(aes(fill = PPCSTOT, geometry = geometry)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "B", labels = scales::dollar) +
  labs(fill = "PER PUPIL - TOTAL CURRENT SPENDING") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"))


mn_acs_ss_act_pred %>%
  ggplot(aes(fill = TOTALEX, geometry = geometry)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "B", labels = scales::dollar) +
  labs(fill = "TOTAL ELEMENTARY-SECONDARY EXPENDITURE") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_rect(fill = "white"))
```